open module com.mastfrog.mongo.promises {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.asyncpromises.mongo;
    requires transitive com.mastfrog.async.promises;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

    // derived from org.mongodb/mongodb-driver-async-3.12.11 in org/mongodb/mongodb-driver-async/3.12.11/mongodb-driver-async-3.12.11.pom
    requires transitive org.mongodb.mongodb.driver.async;

}
