// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.mongo.promises.tests {
    exports com.mastfrog.asyncpromises;

    // Sibling com.mastfrog/giulius-mongodb-async-3.0.0-dev:test

    // Transitive detected by source scan
    requires com.mastfrog.giulius.mongodb.async;

    // Sibling com.mastfrog/giulius-tests-3.0.0-dev:test
    requires com.mastfrog.giulius.tests;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from test-source-scan

    // derived from junit/junit-4.13.2:test in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit;

}
