open module com.mastfrog.mongo.promises.tests {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.asyncpromises;
    requires transitive com.mastfrog.giulius.mongodb.async;
    requires transitive com.mastfrog.giulius.tests;
    requires transitive com.mastfrog.mongo.promises;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
